"""Canonical scene labels requested for video-scene enrichment."""

SCENE_TAXONOMY = {
    "Emotional scenes": (
        "Happy / Celebration",
        "Sad / Crying",
        "Romantic",
        "Emotional reunion",
        "Goodbye / Farewell",
        "Fear / Panic",
        "Anger",
        "Surprise / Shock",
        "Grief / Mourning",
        "Tension / Suspense",
        "Emotional confrontation",
    ),
    "Action scenes": (
        "Fight",
        "Hand-to-hand combat",
        "Chase",
        "Car chase",
        "Motorcycle chase",
        "Running",
        "Shooting",
        "Explosion",
        "Rescue",
        "Escape",
        "Robbery",
        "Kidnapping",
        "Battle",
        "Stunt sequence",
        "Crime scene",
    ),
    "Travel / Transportation scenes": (
        "Driving",
        "Walking",
        "Running through a location",
        "Train journey",
        "Bus journey",
        "Flight / Airport",
        "Ship / Boat journey",
        "Motorcycle ride",
        "Traffic scene",
        "Arrival",
        "Departure",
    ),
    "Location-based scenes": (
        "Home scene",
        "Bedroom",
        "Living room",
        "Kitchen",
        "Restaurant",
        "Hotel",
        "Office",
        "School",
        "College",
        "Hospital",
        "Police station",
        "Courtroom",
        "Prison / Jail",
        "Shop / Market",
        "Street",
        "Road / Highway",
        "Park",
        "Beach",
        "Forest",
        "Mountain",
        "Village",
        "City",
        "Construction site",
        "Factory / Industrial area",
    ),
    "Work / Professional scenes": (
        "Office work",
        "Business meeting",
        "Job interview",
        "Classroom / Teaching",
        "Medical treatment",
        "Police investigation",
        "Court proceedings",
        "Scientific experiment",
        "Factory work",
        "Construction work",
    ),
    "Event scenes": (
        "Party",
        "Wedding",
        "Birthday",
        "Festival",
        "Concert",
        "Stage performance",
        "Sports event",
        "Award ceremony",
        "Funeral",
        "Religious / cultural ceremony",
        "Public gathering",
        "Political/public rally",
    ),
    "Music / Performance scenes": (
        "Singing",
        "Dancing",
        "Musical performance",
        "Band performance",
        "Playing guitar",
        "Playing piano",
        "Playing drums",
        "Playing other instruments",
        "DJ performance",
        "Stage performance",
        "Rehearsal",
    ),
    "Investigation / Mystery scenes": (
        "Investigation",
        "Searching for evidence",
        "Surveillance",
        "Following someone",
        "Discovering something",
        "Crime investigation",
        "Detective work",
        "Evidence examination",
        "Hidden-object discovery",
        "Mystery reveal",
    ),
    "Everyday activity scenes": (
        "Eating",
        "Drinking",
        "Cooking",
        "Sleeping",
        "Waking up",
        "Reading",
        "Writing",
        "Shopping",
        "Cleaning",
        "Working out",
        "Bathing / getting ready",
        "Using a computer",
        "Using a mobile phone",
        "Watching TV",
    ),
    "Special cinematic scenes": (
        "Dream sequence",
        "Nightmare",
        "Hallucination",
        "Memory sequence",
        "Flashback",
        "Montage",
        "Slow-motion sequence",
        "Time-lapse",
        "Imaginary / fantasy sequence",
        "Vision / prophecy",
        "Surreal sequence",
    ),
    "Romance / Relationship": (
        "Romantic scene",
        "Love confession",
        "Dating",
        "Flirting",
        "Couple conversation",
        "Romantic walk",
        "Romantic dinner",
        "Proposal",
        "First meeting",
        "First date",
        "Couple spending time together",
        "Hugging",
        "Kissing",
        "Breakup",
        "Relationship conflict",
        "Jealousy",
        "Reunion of lovers",
        "Wedding proposal",
        "Wedding / marriage",
    ),
    "Comedy / Light-hearted": (
        "Comedy scene",
        "Funny conversation",
        "Prank",
        "Humorous situation",
        "Slapstick",
        "Funny reaction",
        "Party comedy",
        "Friendship comedy",
        "Character misunderstanding",
    ),
    "Emotional / Drama": (
        "Sad scene",
        "Crying",
        "Grief",
        "Death / mourning",
        "Emotional confrontation",
        "Family drama",
        "Separation",
        "Goodbye",
        "Reunion",
        "Apology",
        "Forgiveness",
        "Betrayal",
        "Emotional confession",
    ),
    "Horror": (
        "Horror",
        "Scary encounter",
        "Monster encounter",
        "Ghost / supernatural",
        "Haunted location",
        "Jump scare",
        "Possession",
        "Nightmare",
        "Character being threatened",
        "Escape from danger",
    ),
    "Mystery / Thriller": (
        "Investigation",
        "Detective investigation",
        "Suspense",
        "Searching for evidence",
        "Secret discovery",
        "Mystery reveal",
        "Surveillance",
        "Following someone",
        "Interrogation",
        "Hidden identity",
        "Plot twist",
        "Suspicious activity",
    ),
    "Action": (
        "Fight",
        "Combat",
        "Chase",
        "Car chase",
        "Motorcycle chase",
        "Shooting",
        "Gunfight",
        "Explosion",
        "Rescue",
        "Escape",
        "Robbery",
        "Kidnapping",
        "Attack",
        "Battle",
        "Stunt",
        "Martial arts",
    ),
    "Crime / Police": (
        "Crime",
        "Police investigation",
        "Arrest",
        "Police interrogation",
        "Criminal meeting",
        "Robbery",
        "Theft",
        "Gang confrontation",
        "Prison",
        "Police chase",
        "Evidence collection",
        "Court case",
    ),
    "Family": (
        "Family gathering",
        "Parent-child interaction",
        "Family conversation",
        "Family argument",
        "Family celebration",
        "Family dinner",
        "Sibling interaction",
        "Family conflict",
        "Family reunion",
        "Farewell",
    ),
    "Friendship / Social": (
        "Friends talking",
        "Friends hanging out",
        "Group discussion",
        "Friendship conflict",
        "Reunion",
        "Celebration",
        "Party",
        "Group activity",
    ),
    "Education": (
        "Classroom",
        "Lecture",
        "Exam",
        "Student conversation",
        "Teacher-student interaction",
        "College life",
        "School activity",
        "Graduation",
    ),
    "Professional / Workplace": (
        "Office",
        "Meeting",
        "Job interview",
        "Business discussion",
        "Presentation",
        "Working",
        "Workplace conflict",
        "Boss-employee interaction",
        "Conference",
        "Negotiation",
    ),
    "Medical": (
        "Hospital",
        "Doctor consultation",
        "Medical examination",
        "Surgery",
        "Emergency",
        "Ambulance",
        "Patient treatment",
        "Recovery",
        "Medical emergency",
    ),
    "Legal": (
        "Courtroom",
        "Trial",
        "Lawyer discussion",
        "Judge proceedings",
        "Witness testimony",
        "Police/legal investigation",
        "Verdict",
    ),
    "Celebration / Events": (
        "Birthday",
        "Wedding",
        "Engagement",
        "Party",
        "Festival",
        "Concert",
        "Award ceremony",
        "Graduation",
        "Religious ceremony",
        "Public celebration",
    ),
    "Music / Dance": (
        "Singing",
        "Dancing",
        "Concert",
        "Stage performance",
        "Band performance",
        "Playing guitar",
        "Playing piano",
        "Playing drums",
        "Playing microphone",
        "Music rehearsal",
        "Dance rehearsal",
    ),
    "Sports": (
        "Cricket",
        "Football",
        "Basketball",
        "Tennis",
        "Racing",
        "Boxing",
        "Martial arts",
        "Training",
        "Competition",
        "Sports celebration",
        "Sports injury",
    ),
    "Travel / Transportation": (
        "Driving",
        "Car journey",
        "Motorcycle ride",
        "Train journey",
        "Bus journey",
        "Flight",
        "Airport",
        "Ship / boat",
        "Road trip",
        "Arrival",
        "Departure",
    ),
    "Daily Life": (
        "Eating",
        "Drinking",
        "Cooking",
        "Shopping",
        "Sleeping",
        "Waking up",
        "Reading",
        "Writing",
        "Working",
        "Exercising",
        "Cleaning",
        "Using phone",
        "Using computer",
        "Watching TV",
    ),
    "Environment / Location": (
        "Home",
        "Restaurant",
        "Office",
        "School",
        "Hospital",
        "Police station",
        "Prison",
        "Court",
        "Street",
        "Market",
        "Beach",
        "Forest",
        "Mountain",
        "Village",
        "City",
        "Airport",
        "Train station",
        "Factory",
        "Construction site",
    ),
    "Fantasy / Sci-Fi": (
        "Fantasy",
        "Magic",
        "Supernatural",
        "Alien encounter",
        "Space",
        "Robot interaction",
        "Futuristic city",
        "Time travel",
        "Alternate reality",
        "Superpowers",
        "Monster",
        "Mythological scene",
    ),
    "Psychological / Internal": (
        "Dream",
        "Nightmare",
        "Hallucination",
        "Memory",
        "Flashback",
        "Vision",
        "Imagination",
        "Internal monologue",
        "Psychological confrontation",
    ),
    "Narrative / Structural": (
        "Opening scene",
        "Establishing scene",
        "Character introduction",
        "Exposition",
        "Backstory",
        "Flashback",
        "Flash-forward",
        "Montage",
        "Transition scene",
        "Plot development",
        "Turning point",
        "Climax",
        "Resolution",
        "Ending",
    ),
}

SCENE_LABEL_GROUPS: dict[str, list[str]] = {}
for group, labels in SCENE_TAXONOMY.items():
    for label in labels:
        SCENE_LABEL_GROUPS.setdefault(label.casefold(), []).append(group)

SCENE_LABELS: dict[str, str] = {
    label.casefold(): label
    for labels in SCENE_TAXONOMY.values()
    for label in labels
}
